package testing;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

import edu.cs622.SimpleIntervalUpMajorScale;

public class SimpleIntervalUptest {
	SimpleIntervalUpMajorScale intUpCMajor;

	@Before
	public void setUp() throws Exception {
		intUpCMajor = new SimpleIntervalUpMajorScale(0);
	}

	// Test that the question String is properly formatted after being called in the constructor
	@Test
	public void testQuestionFormatAfterConstructorSetup(){
		String expectedOutput = "In the key of C Major, what is the note a perfect fifth above the median?";
		assertEquals(expectedOutput, intUpCMajor.getQuestion());

	}
	
	// Test that the answer generated by the instantiation of the SimpleIntervalUpMajorScale is correct
	@Test
	public void testForCorrectAnswer(){
		String expectedAnswer = "B";
		assertEquals(expectedAnswer, intUpCMajor.getAnswer());
	}




}
