package testing;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

import edu.cs622.SimpleIntervalUpMajorScale;

public class SimpleIntervalUptest {
	SimpleIntervalUpMajorScale intUpCMajor;

	@Before
	public void setUp() throws Exception {
		intUpCMajor = new SimpleIntervalUpMajorScale(0);
	}

	// Test that the question String is properly formatted after being called in the constructor
	@Test
	public void testQuestionFormatAfterConstructorSetup(){
		String expectedOutput = "In the key of C Major, what is the note a perfect fifth above the mediant?";
		assertEquals(expectedOutput, intUpCMajor.getQuestion());

	}
	
	// Test that the answer generated by the instantiation of the SimpleIntervalUpMajorScale is correct
	@Test
	public void testForCorrectAnswer(){
		String expectedAnswer = "B";
		assertEquals(expectedAnswer, intUpCMajor.getAnswer());
	}
	
	// Test that the answer check works
	@Test
	public void testCheckForCorrectAnswer(){
		String correctAnswer = "B";
		assertEquals(true, intUpCMajor.checkAnswer(correctAnswer));
	}
	
	// Test that the answer check works when the answer is false
	@Test
	public void testCheckForIncorrectAnswer(){
		String incorrectAnswer = "Bb";
		assertEquals(false, intUpCMajor.checkAnswer(incorrectAnswer));
	}
	
	// Test that the feedback explanation to the user on the question is correct
	@Test
	public void testCorrectUserAnswerExplanation(){
		String expectedExplanation = "The mediant of C Major is E.  The note a perfect fifth above E is B.  The answer is B.";
		String actualExplanation = intUpCMajor.getExplanation();
		assertEquals(expectedExplanation, actualExplanation);
	}




}
